### ISSUE TITLE
Retrieve id variable in Twig

### ISSUE THREAD

**Issue by infsy** [kitpages/KitpagesDataGridBundle#45]
Hello

i've got a querybuilder with several jointures i want to present through KitpagesDataGridBundle. It works well, unfortunatly, when i try to add an action column i'm not able to retrieve an id value from my querybuilder. 
I tried a lot of possibilities of naming but nothing works.

Here my controller code :
queryBuilder = $em->createQueryBuilder()
        ->select('l, m, c')
        ->from('NurunRhBundle:ConseillerMandat', 'l')
        ->leftJoin('l.conseiller', 'c')
        ->leftJoin('l.mandat', 'm')
        ->where('l.dateFin BETWEEN :datedeb AND :datefin')
        ->add('orderBy', 'l.dateFin DESC')
        ->setParameter('datefin', $datefin->format('Y-m-d'))
        ->setParameter('datedeb', $datedeb->format('Y-m-d'))
    ;

    $gridConfig = new GridConfig();
    $gridConfig
            ->setQueryBuilder($queryBuilder)
            ->setCountFieldName("l.id")
            ->addField(new Field('l.id', array('visible' => false)))
            ->addField(new Field('c.prenom', array('label' => 'Prénom', 'filterable' => true)))
            ->addField(new Field('c.nom', array('label' => 'Nom', 'filterable' => true)))
            ->addField(new Field('m.identifiant', array('label' => 'Mandat', 'filterable' => true)))
            ->addField(new Field('l.dateFin', array('label' => 'Date de fin', 'filterable' => true)))
        ;

Here my view code : 
{% embed kitpages_data_grid.grid.default_twig with {'grid': grid} %}
            {% block kit_grid_thead_column %}
            <th>Action</th>
            {% endblock %}

            {% block kit_grid_tbody_column %}
                <td><a href="{{ path ("nurun_affectation_view", {"id": l.id}) }}">Edit</a></td>
            {% endblock %}
        {% endembed %}

I've got error message : Variable "l" does not exist in NurunRhBundle:ConseillerMandat:index.html.twig at line 26 

Thank's a lot for your help !
Cedric.

**Comment by b-b3rn4rd** [comment]
Have a quick look at: https://github.com/kitpages/KitpagesDataGridBundle/blob/master/Resources/views/Grid/grid.html.twig.
You have to access `item` array. Example:
{ 'id': item['l.id'] }

**Comment by philippe-levan** [comment]
I love opensource <3
Thanks both for the question and the answer !

**Comment by infsy** [comment]
Thank you very much for your help, it's appreciated. My mystake was reading documentation i didn't realize that item was an array and not a field coming from the exemple querybuilder.... :-]
Have a good day !
