### ISSUE TITLE
Compatibility problem with hydrateRowData()

### ISSUE THREAD

**Issue by infsy** [kitpages/KitpagesDataGridBundle#49]
Hi

i just updated my symfony project with this versions 
- Symfony : 2.5.11
- Doctrine/orm : 2,5,0
- Kitpages : master

Runtime Notice: Declaration of Kitpages\DataGridBundle\Hydrators\DataGridHydrator::hydrateRowData() should be compatible with Doctrine\ORM\Internal\Hydration\AbstractHydrator::hydrateRowData(array $data, array &$result) in /home/cedric/Programmation/kentel/trunk/vendor/kitpages/data-grid-bundle/Kitpages/DataGridBundle/Hydrators/DataGridHydrator.php line 0 

It was functionnal before update.

Any idea ?

**Comment by eliecharra** [comment]
@infsy Thanks for you feedback, I'll working on a fix asap

**Comment by eliecharra** [comment]
> Minor BC BREAK: Custom Hydrators API change

> As of 2.5, AbstractHydrator does not enforce the usage of cache as part of API, and now provides you a clean API for column information through the method hydrateColumnInfo($column). Cache variable being passed around by reference is no longer needed since Hydrators are per query instantiated since Doctrine 2.4.

Hum, there is a BC break in doctrine 2.5.
@philippe-levan Ok to realease a 2.5 version of DataGrid following new doctrine 2.5 API ?

**Comment by eliecharra** [comment]
@infsy Could you try with 
```json
{
    "require": {
        "kitpages/data-grid-bundle": "~2.5"
    }
}
```

**Comment by infsy** [comment]
Great ! It works like a charm J

Many thank's for the very quick update !
Cheers.
