### ISSUE TITLE
Suggestion: add row class block

### ISSUE THREAD

**Issue by b-b3rn4rd** [kitpages/KitpagesDataGridBundle#50]
I reckon it would be useful to be able to specify a class for a table row.
Probably the simplest solution would be to add an empty block to the grid template and extend it only if required. 
For example

```html
{% embed kitpages_data_grid.grid.default_twig with {'grid': grid} %}
    {% block row_class %}
        {% if item['t.deletedAt'] %} stroke {% endif %}
    {% endblock %}
```

**Comment by philippe-levan** [comment]
This is a good idea but : 

* can you rename the block "kit_grid_row_class" ?
* can you add this feature somewhere in the Resources/doc/10-GridExtendedUse.md documentation ?

best regards,
Philippe

**Comment by b-b3rn4rd** [comment]
no worries, I will do this tonight

**Comment by philippe-levan** [comment]
your PR is merged, thanks for this work !
