### ISSUE TITLE
Is there a way to change the url parameter names?

### ISSUE THREAD

**Issue by skollro** [kitpages/KitpagesDataGridBundle#52]
Hello,
is there a way to change the url parameter name "kitdg_grid_grid_sort_order" to a friendlier name like "sort" and so on?
Thank you!

**Comment by b-b3rn4rd** [comment]
Have a look: https://github.com/kitpages/KitpagesDataGridBundle/blob/master/Grid/Grid.php :148 & :152 field names are pretty much hardcoded, however, you can extend `Kitpages\DataGridBundle\Grid\Grid` and override those methods

**Comment by skollro** [comment]
Yes, but the problem is that we can't replace https://github.com/kitpages/KitpagesDataGridBundle/blob/master/Grid/GridManager.php#L69
with our new extended class.

**Comment by b-b3rn4rd** [comment]
yeah, unless you want to extend GridManager, anyway :69 should be replaced with DI.

Thanks for pointing this out

**Comment by eliecharra** [comment]
Closing here, let's continue this discussion in #53
