### ISSUE TITLE
GridManager: replace hardcoded intiation of Grid with DI

### ISSUE THREAD

**Issue by b-b3rn4rd** [kitpages/KitpagesDataGridBundle#53]
https://github.com/kitpages/KitpagesDataGridBundle/blob/master/Grid/GridManager.php#L69 probably should be replaced with DI.

I see two options how this can be solved:
- Pass instance of Grid when manager is created and implement `__clone` method for Grid that erases all properties before creating new grid object
- Another option is to inject Grid class name and create new instance of Grid using variable value

**Comment by eliecharra** [comment]
Sorry for the delay, also added a (too big) [GridInterface](https://github.com/kitpages/KitpagesDataGridBundle/blob/grid_class_di%2353/Grid/GridInterface.php)

**Comment by philippe-levan** [comment]
The PR #56 is not the good option. I believe the idea of giving an optional instance of a subclass of Grid or an implimentation of a future GridInterface would be the good option.

It is a bit of work.

I can add that if there is more user that ask for that. I let this  issue open.

**Comment by haroldmodesto** [comment]
+1

@philippe-levan Do you think you have the time for this now?

**Comment by philippe-levan** [comment]
@haroldmodesto 
This PR resolves this issue.

https://github.com/kitpages/KitpagesDataGridBundle/pull/68

I will merge it soon an create a tag.

**Comment by philippe-levan** [comment]
ok, PR merged, tag 3.1.0.

You can see the documentation here : https://github.com/kitpages/KitpagesDataGridBundle/blob/master/README.md#custom-class-for-the-grid-object

Best regards,
Philippe

**Comment by haroldmodesto** [comment]
That was super quick! Many thanks.
