### ISSUE TITLE
Block kit_grid_tbody_column receives item as an array with full keys

### ISSUE THREAD

**Issue by juuga** [kitpages/KitpagesDataGridBundle#55]
I just upgraded from bundle v1.11.0 to v2.4.2. I had been using the following kind of code (simplified)

```
{% block kit_grid_tbody_column %}
    {{ item.id }}
{% endblock %}
```

but now the key "id" is no longer defined. It has been changed to use `{{ item["fos_user.id"] }}` i.e. the whole key I defined in the query builder and the `new Field`. Is there a way around this so I could use `item.id` in the block?

**Comment by philippe-levan** [comment]
No, since version  2.x there is no way to come back to v1.x syntax.

The v1.x syntax was not coherent and was usable in only simple cases.

Best regards,
Philippe
