### ISSUE TITLE
how to change the name of Filter box and label, also the url params ?

### ISSUE THREAD

**Issue by safaa-alnablsi** [kitpages/KitpagesDataGridBundle#62]
Is there a way to change the name of Filter box and label also the url params, via any function or config ?

**Comment by philippe-levan** [comment]
The URL can't be changed easily.

If you want to change the name of the filter box, or the label, you can use the translation system (override the translation file of the bundle).

Best regards,
Philippe

**Comment by safaa-alnablsi** [comment]
Thanks but in my case, it's not being translated , it's `kitpages_data_grid.filter`

**Comment by philippe-levan** [comment]
You probably have to activate the translator in your symfony app.

**Comment by safaa-alnablsi** [comment]
Thank you so much.
