### ISSUE TITLE
Incompatible with Symfony 3.1.1

### ISSUE THREAD

**Issue by martijnhartlief** [kitpages/KitpagesDataGridBundle#64]
I'm unable to install the bundle on the latest stable version of Symfony.

```
composer require kitpages/data-grid-bundle                                       
Using version ^2.5 for kitpages/data-grid-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v3.1.1
    - Conclusion: don't install symfony/symfony v3.1.1
    - kitpages/data-grid-bundle 2.5.2 requires symfony/twig-bundle ~2.3 -> satisfiable by symfony/twig-bundle[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7].
```

**Comment by oncesk** [comment]
Are you fixed that?

**Comment by martijnhartlief** [comment]
No idea, we have opted for another bundle. I guess I'll close it for now.

**Comment by chrisjohnson00** [comment]
@martijnhartlief what alternative bundle did you go with?  I'm evaluating options and also am using the latest symfony

**Comment by infsy** [comment]
You can go with a bundle working directly in the frontend in JS like Datatables : https://datatables.net. You can add it to Symfony with sg/datatablesbundle. 
This is interesting because you don't modify anything in your controller, you just send your array in to your twig and the bundle handle everything in a js. Very simple and efficient (and portable of course)...

**Comment by chrisjohnson00** [comment]
@infsy true, but I'm dealing with hundreds of thousands of records, so sending 150k records to twig to process isn't really feasible. I've used datatables in the past and it is great, but also has its limitations :)

**Comment by infsy** [comment]
@chrisjohnson00 Yes, of course you're right, it's limited to the frontend capacity to handle a large amount of records... Otherwise, in backend, i used one time [APYDatagrid](https://github.com/APY/APYDataGridBundle) bundle. Good luck in your search !
.
