### ISSUE TITLE
Non case sensitive filter search

### ISSUE THREAD

**Issue by jvrdom** [kitpages/KitpagesDataGridBundle#66]
There is possible in te config of the grid that the filter can be non sensitive, because I have the issue that with the word "Julien" get the results but with 'julien' no.

Here is my gridConfig:

```php
$gridConfig
->setCountFieldName('Authors.id')
->addField(new Field('Authors.cover_image_id',
    array(
        'label' => 'Image',
        'filterable' => false,
        'sortable' => true,
        'autoEscape' => true,
        'formatValueCallback' => function ($value) {
            return 'image_field';
        },
    )))
->addField(new Field('Authors.name', array('label' => 'Name', 'filterable' => true, 'sortable' => true)));
```

There is some extra config that I have to apply?

Thanks.

**Comment by jvrdom** [comment]
@philippe-levan @eliecharra

**Comment by philippe-levan** [comment]
Hi,

By default, filter is not case sensitive, but you can change the way the filter works by listening the KitpagesDataGridEvents::ON_APPLY_FILTER and set the preventDefault.

You can check the code here : https://github.com/kitpages/KitpagesDataGridBundle/blob/master/Grid/GridManager.php#L202

You can see an example of listener in the documentation here : https://github.com/kitpages/KitpagesDataGridBundle/blob/master/Resources/doc/30-Events.md#kitpages_data_gridon_apply_filter

Best regards,
Philippe
