### ISSUE TITLE
Method addField of GridConfig class missing argument for tag list

### ISSUE THREAD

**Issue by haroldmodesto** [kitpages/KitpagesDataGridBundle#69]
Documentation states that you can add tags to a field by:

`$gridConfig->addField("foo", [], ['myTag', 'foo']);`

but the addField implementation is missing the third parameter. Fix should be simple. 

As an alternative while fix is not in you can add tags by instantiating the Field yourself:

```
$field = new Field("foo", [], ['myTag', 'foo']);
$gridConfig->addField($field);
```

**Comment by philippe-levan** [comment]
My bad, fixed in version v3.1.1.

best regards,
Philippe
